//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunBeam.Domain.Models
{
    using SunBeam.Domain;
    using System;
    using System.Collections.Generic;

    public partial class ProductDetail: BaseEntity
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<int> ProductBrandId { get; set; }
        public Nullable<int> ProductCatagoriesId { get; set; }
        public Nullable<int> ProductColorId { get; set; }
        public Nullable<int> ProductSizeId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> OpenQuantity { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public Nullable<decimal> Discount { get; set; }
      
    }
}
