//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunBeam.Domain.Models
{
    using SunBeam.Domain;
    using System;
    using System.Collections.Generic;

    public partial class PurcheaseReturns: BaseEntity
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
         public string EmployeeName { get; set; }
         public string SupplierName { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public string InvoiceNo { get; set; }
        public string Date { get; set; }
        public IEnumerable<PurcheaseReturnDetails> PurcheaseReturnDetails { get; set; }

    }
}
