//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunBeam.Domain.Models
{
    using SunBeam.Domain;
    using System;
    using System.Collections.Generic;

    public partial class Sales: BaseEntity
    {
        public int Id { get; set; }
        public string InvoiecNo { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ZoneOrAreaId { get; set; }
        public string ZoneOrAreaName { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string DiscountRemarks { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> PackUnitPrice { get; set; }
        public Nullable<decimal> PackQuantity { get; set; }
        public string EventName { get; set; }
        public Nullable<decimal> EventAamount { get; set; }
        public IEnumerable<SalesDetails> SalesDetails { get; set; }
        public string MarketName { get; set; }
    }
}
