//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunBeam.Domain.Models
{
    using SunBeam.Domain;
    using System;
    using System.Collections.Generic;

    public partial class StockDetail:BaseEntity
    {
        public int Id { get; set; }
        public Nullable<int> SalesId { get; set; }
        public Nullable<int> SalesReturnId { get; set; }
        public Nullable<int> PurcheaseId { get; set; }
        public Nullable<int> PurcheaseReturnId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<decimal> StockReplace { get; set; }
        public Nullable<decimal> TransReplace { get; set; }
        public Nullable<decimal> TotalReplace { get; set; }
        public Nullable<decimal> StockReturn { get; set; }
        public Nullable<decimal> TransReturn { get; set; }
        public Nullable<decimal> TotalReturn { get; set; }
        public Nullable<decimal> StockDiscount { get; set; }
        public Nullable<decimal> TransDiscount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TransSlup { get; set; }
        public Nullable<decimal> StockSlup { get; set; }
        public Nullable<decimal> TotalSlup { get; set; }
        public Nullable<decimal> StockQuantity { get; set; }
        public Nullable<decimal> TransQuantity { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> StockPrice { get; set; }
        public Nullable<decimal> TransPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
      
        public Nullable<bool> StockStutes { get; set; }
        public string Date { get; set; }
       
    }
}
