//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunBeam.Domain.Models
{
    using SunBeam.Domain;
    using System;
    using System.Collections.Generic;

    public partial class UserRole: BaseEntity
    {
        public int Id { get; set; }
        public int BranchId { get; set; }
        public string UserInfoId { get; set; }
        public string RoleInfoId { get; set; }
        public bool IsArchived { get; set; }
    }
}
