CREATE TABLE [dbo].[Employee] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [BranchId]         INT            NULL,
    [Code]             NVARCHAR (20)  NULL,
    [Name]             NVARCHAR (50)  NULL,
    [Salutation_E]     NVARCHAR (200) NULL,
    [MiddleName]       NVARCHAR (200) NULL,
    [LastName]         NVARCHAR (200) NULL,
    [CountryId]        INT            NULL,
    [DivisionId]       INT            NULL,
    [DistrictId]       INT            NULL,
    [Mobile]           NVARCHAR (20)  NULL,
    [PermanentAddress] NVARCHAR (500) NULL,
    [PresentAddress]   NVARCHAR (500) NULL,
    [PABX]             NVARCHAR (100) NULL,
    [Email]            NVARCHAR (100) NULL,
    [FAX]              NVARCHAR (100) NULL,
    [Remarks]          NVARCHAR (500) NULL,
    [IsActive]         BIT            NULL,
    [IsArchive]        BIT            NULL,
    [CreatedBy]        NVARCHAR (20)  NULL,
    [CreatedAt]        NVARCHAR (50)  NULL,
    [CreatedFrom]      NVARCHAR (50)  NULL,
    [LastUpdateBy]     NVARCHAR (50)  NULL,
    [LastUpdateAt]     NVARCHAR (50)  NULL,
    [LastUpdateFrom]   NVARCHAR (50)  NULL,
    CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([Id] ASC)
);

