CREATE TABLE [dbo].[SalesDetails] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [SalesId]              INT             NULL,
    [ProductId]            INT             NULL,
    [ProductName]          NVARCHAR (50)   NULL,
    [ProductCode]          NVARCHAR (50)   NULL,
    [Discount]             DECIMAL (18, 2) NULL,
    [UnitePrice]           DECIMAL (18, 2) NULL,
    [Date]                 NVARCHAR (50)   NULL,
    [Slup]                 DECIMAL (18, 2) NULL,
    [Bonus]                DECIMAL (18, 2) NULL,
    [AssaignQuantity]      DECIMAL (18, 2) NULL,
    [SalesQuantity]        DECIMAL (18, 2) NULL,
    [Return]               DECIMAL (18, 2) NULL,
    [Replace]              DECIMAL (18, 2) NULL,
    [TotalSlupPrice]       DECIMAL (18, 2) NULL,
    [WithOurDiscountPrice] DECIMAL (18, 2) NULL,
    [TotalAmount]          DECIMAL (18, 2) NULL,
    [Remarks]              NVARCHAR (500)  NULL,
    [IsActive]             BIT             NULL,
    [IsArchive]            BIT             NULL,
    [CreatedBy]            NVARCHAR (50)   NULL,
    [CreatedAt]            NVARCHAR (50)   NULL,
    [CreatedFrom]          NVARCHAR (50)   NULL,
    [LastUpdateBy]         NVARCHAR (50)   NULL,
    [LastUpdateAt]         NVARCHAR (50)   NULL,
    [LastUpdateFrom]       NVARCHAR (50)   NULL,
    CONSTRAINT [PK_SalesDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

