CREATE TABLE [dbo].[Sales] (
    [Id]              INT             NOT NULL,
    [InvoiecNo]       NVARCHAR (200)  NULL,
    [ProductId]       INT             NULL,
    [CustomerId]      INT             NULL,
    [ZoneOrAreaId]    INT             NULL,
    [EmployeeId]      INT             NULL,
    [DiscountRemarks] NVARCHAR (200)  NULL,
    [Discount]        DECIMAL (18, 2) NULL,
    [TotalDiscount]   DECIMAL (18, 2) NULL,
    [TotalPaid]       DECIMAL (18, 2) NULL,
    [GrandTotal]      DECIMAL (18, 2) NULL,
    [Date]            NVARCHAR (50)   NULL,
    [PackUnitPrice]   DECIMAL (18, 2) NULL,
    [PackQuantity]    DECIMAL (18, 2) NULL,
    [EventName]       NVARCHAR (500)  NULL,
    [EventAamount]    DECIMAL (18, 2) NULL,
    [Remarks]         NVARCHAR (500)  NULL,
    [IsActive]        BIT             NULL,
    [IsArchive]       BIT             NULL,
    [CreatedBy]       NVARCHAR (50)   NULL,
    [CreatedAt]       NVARCHAR (50)   NULL,
    [CreatedFrom]     NVARCHAR (50)   NULL,
    [LastUpdateBy]    NVARCHAR (50)   NULL,
    [LastUpdateAt]    NVARCHAR (50)   NULL,
    [LastUpdateFrom]  NVARCHAR (50)   NULL,
    CONSTRAINT [PK_Sales] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ__Sales__3214EC06BE8C58A0] UNIQUE NONCLUSTERED ([Id] ASC),
    CONSTRAINT [UQ__Sales__B358CA75B43AEBDA] UNIQUE NONCLUSTERED ([InvoiecNo] ASC)
);

