CREATE TABLE [dbo].[StockDetails] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [SalesId]           INT             NULL,
    [SalesReturnId]     INT             NULL,
    [PurcheaseId]       INT             NULL,
    [PurcheaseReturnId] INT             NULL,
    [StockId]           INT             NULL,
    [StockReplace]      DECIMAL (18, 2) NULL,
    [TransReplace]      DECIMAL (18, 2) NULL,
    [TotalReplace]      DECIMAL (18, 2) NULL,
    [StockReturn]       DECIMAL (18, 2) NULL,
    [TransReturn]       DECIMAL (18, 2) NULL,
    [TotalReturn]       DECIMAL (18, 2) NULL,
    [StockDiscount]     DECIMAL (18, 2) NULL,
    [TransDiscount]     DECIMAL (18, 2) NULL,
    [TotalDiscount]     DECIMAL (18, 2) NULL,
    [TransSlup]         DECIMAL (18, 2) NULL,
    [StockSlup]         DECIMAL (18, 2) NULL,
    [TotalSlup]         DECIMAL (18, 2) NULL,
    [StockQuantity]     DECIMAL (18, 2) NULL,
    [TransQuantity]     DECIMAL (18, 2) NULL,
    [TotalQuantity]     DECIMAL (18, 2) NULL,
    [TotalPaid]         DECIMAL (18, 2) NULL,
    [StockPrice]        DECIMAL (18, 2) NULL,
    [TransPrice]        DECIMAL (18, 2) NULL,
    [TotalPrice]        DECIMAL (18, 2) NULL,
    [Remarks]           NVARCHAR (500)  NULL,
    [StockStutes]       BIT             NULL,
    [Date]              NVARCHAR (50)   NULL,
    [IsActive]          BIT             NULL,
    [IsArchive]         BIT             NULL,
    [CreatedBy]         NVARCHAR (50)   NULL,
    [CreatedAt]         NVARCHAR (50)   NULL,
    [CreatedFrom]       NVARCHAR (50)   NULL,
    [LastUpdateBy]      NVARCHAR (50)   NULL,
    [LastUpdateAt]      NVARCHAR (50)   NULL,
    [LastUpdateFrom]    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_StockDetails_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

